awesome-academy/hcm_9-naitei-nodejs-cooking_social_network

backend/package-lock.json, backend/src/app.module.ts, backend/src/common/dto/user-responses.dto.ts, backend/src/common/guards/jwt-auth.guard.ts, backend/src/common/utils/password-validator.util.ts, backend/src/main.ts, backend/src/modules/users/dto/update-user.dto.ts, backend/src/modules/users/dto/user-response.dto.ts, backend/src/modules/users/users.controller.ts, backend/src/modules/users/users.module.ts, backend/src/modules/users/users.service.ts, package-lock.json
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/89473)
Implement endpoint to retrieve a paginated list of users in the system. This feature supports pagination and optional authentication to provide user listing functionality for the cooking social network platform.
GET /api/users
| Parameter | Description | Example         |
| --------- | ----------- | --------------- |
| `page`  | `Page number (default: 1)`         | `?page=1` |
| `limit`  | `Items per page (default: 10)`         | `?limit=10` |
| `name`  | `Search by firstName, lastName, or username (case-sensitive)`         | `?name=Nhi` |
Authentication optional
```json
{
"users": [
{
"id": 2,
"email": "pnhi@gmail.com",
"firstName": "Phương",
"lastName": "Nhi",
"username": "pnhi",
"birthday": null,
"followes": 0, …
```
=> feat: implement view, delete, update user information

backend/prisma/migrations/20250807043807_add_reply_of_replies_count_to_post_comment/migration.sql, backend/prisma/schema.prisma, backend/src/modules/comments/comments.controller.ts, backend/src/modules/comments/comments.service.ts, backend/src/modules/comments/dto/create-comment.dto.ts
This feature adds the ability to create a reply to an existing comment under a specific post. When a reply is created, the parent comment’s `repliesCount` is incremented, and the post’s `commentsCount` is updated accordingly.
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/90457)
`POST /api/posts/:postId/comments/:commentId/replies`
Create a reply to a comment.
| Parameter   | Description              | Example                 |
| ----------- | ------------------------ | ----------------------- |
| `postId`    | ID of the post           | `/posts/10/comments/21` |
| `commentId` | ID of the parent comment | `/posts/10/comments/21` |
Authentication required (JWT).
```json
{
"comment": {
"comment": "YES"
}
}
```
```json
{
"comment": {
"id": 7,
"post_id": 2,
"reply_of": 1, …
```
=> feat/replies: create and get replies

frontend/src/services/ingredient.service.ts, frontend/src/services/recipe.service.ts, frontend/src/types/ingredient.type.ts, frontend/src/types/recipe.type.ts
[Ticket redmine link
](https://edu-redmine.sun-asterisk.vn/issues/90842)
- Wrote API services for frontend to handle recipes and ingredients, including CRUD operations and ratings management.
=> feat(frontend): implemented recipe and ingredient services

backend/src/modules/posts/dto/update-post.dto.ts, backend/src/modules/posts/posts.service.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Post/Comments.tsx, frontend/src/components/Post/Post.tsx, frontend/src/components/Post/ReplyItem.tsx, frontend/src/components/common/forms/CommentInput.tsx, frontend/src/components/common/ui/PostActionBar.tsx, frontend/src/components/popup/DeleteConfirm.tsx, frontend/src/components/popup/EditPostPopup.tsx, frontend/src/components/popup/RecipeSelectionModal.tsx, frontend/src/components/popup/SharePopup.tsx, frontend/src/components/popup/index.ts, frontend/src/services/post.service.ts, frontend/src/services/recipe.service.ts, frontend/src/services/user.service.ts, frontend/src/types/post.type.ts, frontend/src/types/recipe.type.ts, frontend/src/utils/errorHandler.ts, frontend/src/utils/utils.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/90899)
Implement and complete the Post component with full editing, sharing, and interaction features.
1. Post Editing
✅ Implement EditPostPopup
✅ Support media upload (images/videos)
✅ Integrated emoji picker in text areas
✅ "Attach Recipe" functionality with search and filter modal
✅ Text-only editing in post detail modal
✅ Direct media upload handling within component
2. Post Sharing
✅ Share via social media (Facebook, Twitter, Copy link)
✅ Share via messages with WebSocket integration
✅ Auto-create/find conversation with user
✅ Send messages with POST type and post link
3. Delete Functionality
✅ Custom delete confirmation popup replacing confirm()
✅ Applied to posts, comments, and replies
✅ User-friendly UI
4. Recipe …
=> feat: Update FE component Post

backend/prisma/migrations/20250819021919_add_reaction/migration.sql, backend/prisma/schema.prisma, backend/src/modules/messages/dto/toggle-reaction.dto.ts, backend/src/modules/messages/messages.gateway.ts, backend/src/modules/messages/messages.service.ts, frontend/src/components/Message/ChatHeader.tsx, frontend/src/components/Message/ConversationList.tsx, frontend/src/components/Message/MessageInput.tsx, frontend/src/components/Message/MessageReactions.tsx, frontend/src/components/Message/ReactionModal.tsx, frontend/src/components/Message/ReactionSummary.tsx, frontend/src/components/Message/SeenByAvatars.tsx, frontend/src/components/Message/SeenByModal.tsx, frontend/src/components/Message/index.tsx, frontend/src/pages/main/Message/MessagePage.tsx, frontend/src/types/conversation.type.ts, frontend/src/utils/utils.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/91604)
- Add a message reaction feature and allow users to add emojis to messages.
- Optimize the user experience for read messages by providing a detailed view of who has read and who has reacted.
- Group chat UI
- Message seen details
- Message reaction details
- Add emoji to input message
=> feat: implement reaction and update seen UX

frontend/src/components/layout/Header.tsx, frontend/src/components/sections/Profile/RecipesTab.tsx, frontend/src/router/AppRouter.tsx
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/91982)
This pull request focuses on improving the user experience for the header dropdown menu and navigation within the application.
1. Display real user avatar:
- Replace hardcoded avatar with actual user avatar from AuthContext
- Add default avatar when user doesn't have one
2. Profile page navigation:
- Add navigation to personal profile page when clicking "Trang cá nhân" (Profile)
- Use actual username from AuthContext to generate correct URL
3. Improve dropdown menu behavior:
- Close dropdown menu when clicking "Tài khoản" (Account) - previously only closed for "Trang cá nhân" and "Đăng xuất"
- Ensure consistency in closing dropdown after each interaction
=> feat: update Header component to use user avatar and add profile navigation

backend/src/modules/conversations/conversations.controller.ts, backend/src/modules/conversations/conversations.service.ts, backend/src/modules/messages/messages.gateway.ts, frontend/src/components/Message/ConversationList.tsx, frontend/src/components/Message/CreateConversation.tsx, frontend/src/components/Message/InfoSidebar.tsx, frontend/src/components/Message/Members.tsx, frontend/src/components/Message/index.tsx, frontend/src/components/popup/DeleteConfirm.tsx, frontend/src/pages/main/Message/MessagePage.tsx, frontend/src/services/conversation.service.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92033)
- Implement the conversation creation feature.
- Implement group member management: View, add, and remove. If the group only has 2 members, adding a new member will create a new group instead of adding to the private chat between the two members.
- Implement the leave conversation feature.
- Create conversation
- Member list
- Add member
- Delete member
- Leave conversation
=> feat: implement add & delete memmber, create & leave conversation

frontend/src/components/Post/Post.tsx, frontend/src/components/modals/Post/CreatePostModal.tsx, frontend/src/components/sections/Feed/Sidebar.tsx, frontend/src/constants/constants.ts, frontend/src/pages/main/Feed/Feed.tsx, frontend/src/services/post.service.ts, frontend/src/services/user.service.ts, frontend/src/types/post.type.ts, frontend/src/types/recipe.type.ts
[Redmine ticket](https://edu-redmine.sun-asterisk.vn/issues/92038)
This PR implements several new frontend features for the social cooking platform:
1.  **Create Post**
* Users can write a caption, upload images, and attach a recipe.
* Recipes can be selected from:
* Public recipes available on the system
* User's own recipes
* Recipes found via search
* After submission, the newly created post is automatically added to the feed without requiring a page reload.
2.  **Suggested Users - Follow**
* Added the ability to follow suggested users directly from the right sidebar.
* Once a user is followed, they are removed from the suggestion list.
3.  **Suggested Recipes**
* Display a list of recommended recipes based on:
* The number of users who saved the recipe (higher saved count = higher …
=> fe/newsfeed: implement create post, follow users functionalities

backend/src/modules/messages/dto/get-messages-query.dto.ts, backend/src/modules/messages/messages.service.ts, frontend/src/components/Message/Link.tsx, frontend/src/components/Message/Media.tsx, frontend/src/components/Message/index.tsx, frontend/src/components/Post/Post.tsx, frontend/src/components/popup/SharePopup.tsx, frontend/src/pages/main/Message/MessagePage.tsx, frontend/src/pages/main/PostDetail/PostDetail.tsx, frontend/src/services/message.service.ts, frontend/src/utils/getImageReview.tsx, frontend/src/utils/utils.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92287)
- Implement the media library interface and display links to recipes and articles within the conversation
- Modify the share structure in article sharing
- Media Gallery
- Link
=> feat: implement media, link tab

backend/src/app.module.ts, backend/src/modules/notifications/dto/create-notification.dto.ts, backend/src/modules/notifications/dto/get-notifications.dto.ts, backend/src/modules/notifications/notifications.controller.spec.ts, backend/src/modules/notifications/notifications.controller.ts, backend/src/modules/notifications/notifications.gateway.ts, backend/src/modules/notifications/notifications.module.ts, backend/src/modules/notifications/notifications.service.spec.ts, backend/src/modules/notifications/notifications.service.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92338)
- Implement APIs: getNotification, markAsRead, markAllAsRead
- Implement sending and receiving notifications in real-time
`<GET> /api/notifications`
Authentication required
`<GET> /api/notifications`
Authentication required
```json
{
"notifications": [
{
"id": 1,
"content": "Huỳnh Văn Thiệu đã follow bạn.",
"url": "/profile/ryderthieu",
"isRead": false,
"createdAt": "2025-08-27T02:15:00.000Z",
"senderUser": {
"id": 5,
"username": "johndoe",
"firstName": "John",
"lastName": "Doe",
"avatar": "https://example.com/avatar.jpg"
}
}
],
"meta": {
"total": 342,
"page": 1,
"limit": 10,
"totalPages": 35
}
}
```
`<Post> /api/notifications/notificationId/read`
Authentication required
```json
{
"notification": 
{
"id": 1, …
```
=> feat implement notification service

frontend/src/components/popup/FollowersPopup.tsx, frontend/src/components/sections/Profile/ProfileHeader.tsx, frontend/src/components/sections/Profile/ProfileStats.tsx, frontend/src/pages/main/Profile/ProfilePage.tsx
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92360)
This PR improves the user experience of the follower/following popup
- Fixed black border issue: Removed divide-y class and replaced with space-y-2 to eliminate unwanted divider lines between user items
- Real-time stats updates: Added onStatsChange callback system to update follower/following counts immediately when users follow/unfollow
- Improved state managemen
=> fix: add onStatsChange prop to manage follower and following counts across Profile components

backend/src/modules/comments/comments.module.ts, backend/src/modules/comments/comments.service.ts, backend/src/modules/notifications/dto/get-notifications.dto.ts, backend/src/modules/notifications/notifications.gateway.ts, backend/src/modules/notifications/notifications.module.ts, backend/src/modules/notifications/notifications.service.ts, backend/src/modules/posts/posts.module.ts, backend/src/modules/posts/posts.service.ts, backend/src/modules/users/users.module.ts, backend/src/modules/users/users.service.ts, frontend/src/components/Post/ReplyItem.tsx, frontend/src/pages/main/Notification/Notification.tsx, frontend/src/pages/main/PostDetail/PostDetail.tsx, frontend/src/router/AppRouter.tsx, frontend/src/services/notification.service.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92393)
- Implement the notification interface, allowing users to receive notifications when someone follows them, likes a post, comments, shares, replies to a comment, or likes a comment.
=> feat: implement notification page

backend/src/modules/comments/comments.module.ts, backend/src/modules/comments/comments.service.ts, backend/src/modules/notifications/dto/get-notifications.dto.ts, backend/src/modules/notifications/notifications.gateway.ts, backend/src/modules/notifications/notifications.module.ts, backend/src/modules/notifications/notifications.service.ts, backend/src/modules/posts/posts.module.ts, backend/src/modules/posts/posts.service.ts, backend/src/modules/users/users.module.ts, backend/src/modules/users/users.service.ts, frontend/src/components/Message/ConversationList.tsx, frontend/src/components/Post/ReplyItem.tsx, frontend/src/components/sections/MessageDropdown.tsx, frontend/src/components/sections/NotificationDropdown.tsx, frontend/src/pages/main/Message/MessagePage.tsx, frontend/src/pages/main/Notification/Notification.tsx, frontend/src/pages/main/PostDetail/PostDetail.tsx, frontend/src/router/AppRouter.tsx, frontend/src/services/notification.service.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92402)
- Implement message and notification dropdown
=> feat: implement notification and message drop down

frontend/src/pages/main/SearchPage/SearchPage.tsx
[Ticket Link](https://edu-redmine.sun-asterisk.vn/issues/92407)
This pull request introduces filtering and sorting capabilities for the posts feed and recipes, enhancing user experience by providing more control over content discovery.
-   **Sort by date**: Users can now sort the posts feed chronologically.
-   `newest`: Displays the most recent posts first.
-   `oldest`: Displays the oldest posts first.
-   **Filter by following**: A new filter has been added to allow users to view posts exclusively from the creators they follow.
-   **Filter by main ingredient**: Users can filter recipes based on the primary ingredient used (e.g., chicken, beef, vegetables).
-   **Filter by cooking time**: Allows users to find recipes that fit their schedule by filtering based on the total cooking time …
=> fe/search-page: add filter functionalities

frontend/src/components/Post/Post.tsx, frontend/src/components/popup/SharePopup.tsx, frontend/src/components/sections/MessageDropdown.tsx, frontend/src/pages/main/PostDetail/PostDetail.tsx
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92451)
- Edit the success notification display when sharing a post
- Do not increase the unread count when the last message is from myself
=> feat: add success and error notification handlers to SharePopup

frontend/src/components/modals/Recipe/CategoryModal.tsx, frontend/src/index.css, frontend/src/pages/recipe/CreateRecipe.tsx, frontend/src/utils/enumMaps.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92464)
- Fix not opening the category selection modal when creating a recipe
=> feat: enhance recipe creation with new category options and validation

backend/src/modules/notifications/notifications.controller.ts
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92468)
- Fix wrong notification fetching error
=> fix: wrong notification fetching

frontend/src/pages/main/SearchPage/SearchPage.tsx
- Add new filter to search recipe
=> feat: implement filter ecipe by category

frontend/src/components/sections/NotificationDropdown.tsx
- Mark notification as read when click on notification
=> fix: mark as read notification

frontend/src/components/modals/Post/CreatePostModal.tsx, frontend/src/components/sections/Feed/Sidebar.tsx
Add emoji picker in create-post-modal
=> fe/create-post: add emoji picker

backend/prisma/migrations/20250829052039_add_is_group_field/migration.sql, backend/prisma/schema.prisma, backend/src/modules/conversations/conversations.service.ts, backend/src/modules/conversations/dto/create-conversation.dto.ts, frontend/src/components/sections/MessageDropdown.tsx, frontend/src/pages/main/Profile/ProfilePage.tsx
[Ticket redmine link](https://edu-redmine.sun-asterisk.vn/issues/92516)
- Add `isGroup` to table `Conversation`
- Update the `addMember` API so that if `isGroup` is false, a new conversation will be created instead of only when the current conversation has 2 members.
=> fix: Fix logic error when adding a member to the group
